name: Export & Deploy Notebooks
on:
    pull_request:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up notebook state cache
              uses: actions/cache@v2
              with:
                path: pluto_state_cache
                key: ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ hashFiles('**/*.jl') }}
                restore-keys: |
                    ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1.7
            - name: Run Pluto notebooks and generate website
              run: |
                # Save create package environment from notebook
                #   (write_nb_to_dir modifies changes the cell order 
                #    if macros are involved hence we want to call it 
                #    on a copy of the notebook)
                cp generate.jl generate2.jl
                julia -e '
                    import Pkg; Pkg.add("Pluto"); import Pluto;
                    Pluto.PkgUtils.write_nb_to_dir("./generate2.jl", ".")
                    '
                # generate website
                julia --project=. -e '
                    import Pkg;
                    Pkg.instantiate();
                    include("generate.jl")
                    '
              working-directory: generate
              
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: website
                  path: ./website/__site
                  
            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@releases/v3
              if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: ./website/__site
